### ISSUE TITLE
Field recordType is not read or written

### ISSUE THREAD

**Issue by Eucrow** [davidcurrie2001/MI_RDBES_ExchangeFiles#2]
Hi! :)

The first field of the tables, XXrecordType is not read or written with the functions readExchangeFile() or generateComplexExchangeFile().

Is it for any specific reason?

**Comment by davidcurrie2001** [comment]
Hi - it should be writing and reading the xxrecordType values - that's the only way to identify what type of data the line in the text file represents.  Can you give me an example where this isn't happening?

(Note that two files are outputted from the generateComplexExchangeFile() - one of these is a "debug_" file which has record id numbers left in - the recordType values won't be in the first position in that file)

**Comment by davidcurrie2001** [comment]
Actually, I just checked and you're right - when I read in from an exchange file I don't create an xxrecordType field - I just put the data in the relevant data frame in the named list of data.  (I normally read in data from our database which does have these fields included.)
I didn't notice before but I think I always use the named lists to keep track of which type of data a row is, rather than worrying about the value of xxrecordType.  I also don't try and validate the xxrecordType fields.
I can't remember any specific reason I did it that way - possibly because the XSD schema files don't provide validation information for the xxrecordType fields.

Does it cause any problems form you?

**Comment by Eucrow** [comment]
Hi!
Thanks for your answer :)
Well, if I use the function generateComplexExchangeFile() with the list generated by readExchangeFile() function, the recordType fiel is not generated, so I think the upload to RDBES will throw an error. This is an extract of the file generated by generateComplexExchangeFile() (some data has been edited for privacy)

```
Onboard_Sampling,NatRouCF,2020,abcd,Y,1,Y,
ES,353
1,,Y,Q3,N,U,Observer,,1,,,SRSWOR,12345,,,,,,Y,
123456789,N,U,N,U,Observer,At-Sea,4,,2020-08-26,,ESPSM,2020-08-26,,,,,,SRSWOR,,,,,,,Y,
N,1,U,N,U,Observer,H,V,All,,,2020-08-26,02:10,210,Crew,,,,9999,-9999,EU,27.9.a,,NotApplicable,,35,,,,,OTB,,,,MCD,Unknown,NotApplicable,Unknown,NotApplicable,,PrSo,,,,,SYSS,0001,,,,,,Y,
1,N,haul,Lan,vol,U,N,U,Observer,,N,,,,,CENSUS,SS_lan,,,,,,Y,
1,,N,U,127057,SBA,FRE,Whole,NotDetermined,Lan,HuC,,,U,EU,,,NotApplicable,,,,,,,,,Box,,,,,,,CENSUS,1,D,Observer,N,,,,,
10,,N,U,140271,SQR,FRE,Whole,NotDetermined,Lan,HuC,,,U,EU,,,NotApplicable,,,,,,,,,Box,,,,,,,CENSUS,10,D,Observer,Y,,,,,
FRE,Whole,60,4,MantleLength,,RSM,cm,1,MantleLength,Observer,,
```

As you can see, the function doesn't create the field recordType. Maybe this is because the data used in generateComplexExchangeFile() doesn't has the recordType by itself?

**Comment by davidcurrie2001** [comment]
I'll take a look this afternoon - should be straightforward to fix the readExchangeFile() function to add this field.

**Comment by davidcurrie2001** [comment]
I've just pushed some changes to RDBES_Functions.R which I think fixes this - can you pull down the changes and see if it now works for you?

**Comment by Eucrow** [comment]
Hi :)

Ah, great, now the field is created when the file is imported and when it is exported.

Thank you so much :)

**Comment by davidcurrie2001** [comment]
No problems - glad its sorted now.
